name: build  

on: [push, pull_request]  

jobs:  
  build:  
    runs-on: windows-latest  

    steps:  
      - uses: actions/checkout@v3  
        with:  
          submodules: 'recursive'  

      - name: Setup MSVC  
        uses: ilammy/msvc-dev-cmd@v1  
        
      - name: Generating Makefiles  
        run: |  
          Write-Host "Generating Makefiles..."  
          curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --output skia.zip  
          7z x skia.zip  
          cmake -S . -B build -G Ninja `  
            -DCMAKE_BUILD_TYPE Release `  
            -DENABLE_UI on `  
            -DENABLE_CCACHE off `  
            -DLAF_BACKEND skia `  
            -DSKIA_DIR ./skia `  
            -DSKIA_LIBRARY_DIR ./skia/out/Release-x64 `  
            -DSKIA_LIBRARY ./skia/out/Release-x64/skia.lib  

      - name: Compiling  
        run: |  
          cd build  
          ninja  

      - name: Uploading Artifact  
        uses: actions/upload-artifact@v3  
        with:  
          name: aseprite  
          path: |  
            build/bin/data  
            build/bin/aseprite.exe
